"""Pack the web app in firmware/web/ into src/web/WebPage.h.

Edit the files here (index.html, app.css, js/*.js) - never WebPage.h.

Runs by itself before every PlatformIO build (platformio.ini:
extra_scripts = pre:web/embed.py), or by hand:   python web/embed.py

Each file is gzipped (the ESP32 sends it as-is with Content-Encoding: gzip),
so the page costs ~1/4 of its size in flash and on the air. js/*.js are
joined in file-name order into one app.js: the number prefix is the load order.
"""
import glob
import gzip
import hashlib
import os

try:  # inside PlatformIO (SCons): __file__ is not defined there
    Import("env")  # noqa: F821
    ROOT = env.subst("$PROJECT_DIR")  # noqa: F821
except NameError:
    ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

WEB = os.path.join(ROOT, "web")
OUT = os.path.join(ROOT, "src", "web", "WebPage.h")


def read(path):
    with open(path, "rb") as f:
        return f.read()


def js_bundle():
    parts = []
    for path in sorted(glob.glob(os.path.join(WEB, "js", "*.js"))):
        parts.append(b"// ---- " + os.path.basename(path).encode() + b"\n" + read(path))
    return b"\n".join(parts)


def c_array(name, data):
    rows = []
    for i in range(0, len(data), 20):
        rows.append("  " + ",".join(str(b) for b in data[i:i + 20]) + ",")
    return (f"static const uint8_t {name}[] PROGMEM = {{\n" + "\n".join(rows) + "\n};\n"
            f"static const size_t {name}_LEN = {len(data)};\n")


def build():
    assets = [
        ("WEB_INDEX_GZ", read(os.path.join(WEB, "index.html"))),
        ("WEB_CSS_GZ", read(os.path.join(WEB, "app.css"))),
        ("WEB_JS_GZ", js_bundle()),
    ]
    etag = hashlib.sha1(b"".join(d for _, d in assets)).hexdigest()[:12]
    out = [
        "#pragma once\n",
        "// GENERATED by web/embed.py from firmware/web/ - do not edit this file.\n",
        "// Edit web/index.html, web/app.css or web/js/*.js; the next build regenerates it.\n",
        "#include <Arduino.h>\n\n",
        f'static const char WEB_ETAG[] = "\\"{etag}\\"";\n\n',
    ]
    sizes = []
    for name, raw in assets:
        gz = gzip.compress(raw, compresslevel=9, mtime=0)
        sizes.append(f"{name} {len(raw)} -> {len(gz)} B")
        out.append(c_array(name, gz) + "\n")
    text = "".join(out)
    old = read(OUT).decode("utf-8") if os.path.exists(OUT) else ""
    if old != text:  # untouched file = no recompile
        with open(OUT, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
        print("[web] WebPage.h updated: " + ", ".join(sizes))
    else:
        print("[web] WebPage.h up to date")


build()
