waypoints:
  - x: 1.8
    y: 0.0
    mode: goto          
    speed: 0.25
  - x: 1.8
    y: 1.2
    mode: goto       
    speed: 0.25         
  - x: 0.0
    y: 0.0
    mode: goto
    speed: 0.25

# ตัวอย่างการเรียก:
# ros2 run mor_luam drive_sequence.py \
#   --unit mps --speed 0.25 --wheel-diameter 0.0762 \
#   --goto-tolerance 0.05 --through-tolerance 0.15 \
#   --waypoints-yaml $(ros2 pkg prefix mor_luam)/share/mor_luam/config/drive_sequence.yaml
